### ISSUE TITLE
Result issue

### ISSUE THREAD

**Issue by benningtonlee7** [P2333/Bag-of-Tricks-for-AT#5]
Was trying to reproduce your reported PGD-10 results. if I removed the normalize function when evaluating PGD, I got 0.8566 which is close to the clean accuracy, but I expected it to be 50+. If I did not remove the normalize function, I got 0.2319, which was also unexpected. Can you take a look at the provided checkpoints? thanks!

Also, just want to be sure, the PGD-10 you guys performed during evaluation in the paper is the default PGD-10? Meaning, attack_iter = 10, restarts=1, eps=8, step=2? Essentially, I just have a problem reproducing some of the results. Thank you!

**Comment by P2333** [comment]
Thank you for the feedback.

This result is caused by the 'normalize' operation in the [attack_pgd](https://github.com/P2333/Bag-of-Tricks-for-AT/blob/18973ea37a363a0797e1539db99dc7724ec58a3d/utils_plus.py#L58) function. I have updated the [eval_cifar.py](https://github.com/P2333/Bag-of-Tricks-for-AT/blob/18973ea37a363a0797e1539db99dc7724ec58a3d/eval_cifar.py) and [utils_plus.py](https://github.com/P2333/Bag-of-Tricks-for-AT/blob/18973ea37a363a0797e1539db99dc7724ec58a3d/utils_plus.py) scripts, and now you can use a FLAG `--ATmethods` to automatically control the normalization function.
